title: Hexcellent Expeditions and Byte-Sized Adventures
description: Musings about what makes the computing machines tick
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
